### ISSUE TITLE
config-server test for cloudfoundry is failing.

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow-acceptance-tests#137]
After updating to 1.3.0 build snapshot

**Comment by markpollack** [comment]
The test is very expensive in terms of time.  One could change a property such as the application name and then keep the server up and running instead of destorying it and re-createing it again

**Comment by sabbyanandan** [comment]
My observations:
1) /features endpoint is removed from core in favor of /about
2) The `cloud1` profile seems to be set correctly to resolve the property `spring.cloud.dataflow.features.streams-enabled=false` from scdf-server-cloud1.properties file.
3) If the env-var overrode this property correctly, the `about` endpoint _should_ return `{"analyticsEnabled":true,"streamsEnabled":false,"tasksEnabled":true,"skipperEnabled":false}`; however, it appears not to be the case. 
4) It could be because of the extra chars in the response? Maybe Boot upgrade related? (it works just fine on 1.2.3). I see the following in CI's build logs. 
```
error	10-Jan-2018 00:38:46	--2018-01-10 00:38:46--  http://dataflow-server-clement-nonheroicalness.cfapps.io/about
error	10-Jan-2018 00:38:46	Resolving dataflow-server-clement-nonheroicalness.cfapps.io (dataflow-server-clement-nonheroicalness.cfapps.io)... 52.70.0.168, 52.22.195.2, 54.210.242.32, ...
error	10-Jan-2018 00:38:46	Connecting to dataflow-server-clement-nonheroicalness.cfapps.io (dataflow-server-clement-nonheroicalness.cfapps.io)|52.70.0.168|:80... connected.
error	10-Jan-2018 00:38:46	HTTP request sent, awaiting response... 200 OK
error	10-Jan-2018 00:38:46	Length: 1652 (1.6K) [application/hal+json]
error	10-Jan-2018 00:38:46	Saving to: â€˜about.txtâ€™
error	10-Jan-2018 00:38:46	
error	10-Jan-2018 00:38:46	     0K .                                                     100%  355M=0s
```
