### ISSUE TITLE
Improve the download function to support snapshots and different server versions

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow-acceptance-tests#23]
The current function
```
function download(){
  if [ ! -f "$1/scdf-server.jar" ]; then
    echo "Downloading latest release from $SPRING_CLOUD_DATAFLOW_SERVER_DOWNLOAD_URL"
    wget $SPRING_CLOUD_DATAFLOW_SERVER_DOWNLOAD_URL --progress=bar -O $1/scdf-server.jar
  fi
}
```
if the local file is there, then it is never downloaded again, but the URL could have changed.  Also, we will be needing to download snapshots builds.  How is this handled in the spring cloud brewery project?

**Comment by viniciusccarvalho** [comment]
@markpollack I've put a good amount of time thinking about this, I thought about some fancy solutions by using a versions file, keeping multiple possible versions etc.

In  the end I think it won't matter, because the tests are actually what dictates the versioning. Allowing such degree of flexibility could bite us back when  users change the version to 1.1.x and the tests are based on 1.2.x.

I'm not saying the download function should not be enhanced, but I think we are better off, having the version coupled with the pom version. And then use tags whenever we bump the dataflow server we are testing we tag the repo and bump the version of the downloads.

**Comment by markpollack** [comment]
The key requirement we need to meet is to always be downloading the snapshot version of the server.  One approach that is crude, but works, is simply not to keep any cache of the file and always download a new version. 

Another alternative is to have a small Java app that use the  maven spring resource abstractions (which sits upon Aether) and optimizes the download experience.

**Comment by markpollack** [comment]
Regarding " users change the version to 1.1.x and the tests are based on 1.2.x", when we release dataflow, we can release a version (at least tag) the acceptance tests - much like they were in the test suite of SCDF itself.  That way there are known versions of acceptance tests that match known version of the server.
